name: Docs

on:
  push:
    branches:
      - 'main'
    paths:
      - 'documentation/**'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: Build & Publish ðŸš€
    runs-on: ubuntu-latest
    env:
      INPUTPATH: documentation/asciidocs
      # Hier landen die HTML Dateien
      OUTPUTPATH: dist
      SLIDES: true
      BRANCH: gh-pages
    steps:
      - uses: actions/checkout@v4

      - name: run docker
        run: |
          chmod +x ${{ env.INPUTPATH }}/scripts/docker-convert.sh
          sudo ${{ env.INPUTPATH }}/scripts/docker-convert.sh ${{ env.INPUTPATH }} ${{ env.SLIDES }}
          tree

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          branch: ${{ env.BRANCH }}
          # WICHTIG: Lade den Ordner mit den HTML-Dateien hoch!
          folder: ${{ env.OUTPUTPATH }}